### ISSUE TITLE
ERROR: LeakSanitizer: detected memory leaks

### ISSUE THREAD

**Issue by noloader** [ndevilla/iniparser#123]
`make check` using sanitizers is failing with:

```sh
==18158==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 120 byte(s) in 3 object(s) allocated from:
    #0 0x7fade208ee56 in __interceptor_calloc (/lib64/libasan.so.5+0x10de56)
    #1 0x4043a5 in dictionary_new ../src/dictionary.c:157

Indirect leak of 524288 byte(s) in 1 object(s) allocated from:
    #0 0x7fade208ee56 in __interceptor_calloc (/lib64/libasan.so.5+0x10de56)
    #1 0x4040ae in dictionary_grow ../src/dictionary.c:75

Indirect leak of 524288 byte(s) in 1 object(s) allocated from:
    #0 0x7fade208ee56 in __interceptor_calloc (/lib64/libasan.so.5+0x10de56)
    #1 0x40409e in dictionary_grow ../src/dictionary.c:74

Indirect leak of 262144 byte(s) in 1 object(s) allocated from:
    #0 0x7fade208ee56 in __interceptor_calloc (/lib64/libasan.so.5+0x10de56)
    #1 0x4040be in dictionary_grow ../src/dictionary.c:76

Indirect leak of 3672 byte(s) in 360 object(s) allocated from:
    #0 0x7fade208ec58 in __interceptor_malloc (/lib64/libasan.so.5+0x10dc58)
    #1 0x4042d9 in xstrdup ../src/dictionary.c:54

Indirect leak of 2048 byte(s) in 2 object(s) allocated from:
    #0 0x7fade208ee56 in __interceptor_calloc (/lib64/libasan.so.5+0x10de56)
    #1 0x4043fb in dictionary_new ../src/dictionary.c:162

Indirect leak of 2048 byte(s) in 2 object(s) allocated from:
    #0 0x7fade208ee56 in __interceptor_calloc (/lib64/libasan.so.5+0x10de56)
    #1 0x4043d6 in dictionary_new ../src/dictionary.c:161

Indirect leak of 1024 byte(s) in 2 object(s) allocated from:
    #0 0x7fade208ee56 in __interceptor_calloc (/lib64/libasan.so.5+0x10de56)
    #1 0x404420 in dictionary_new ../src/dictionary.c:163

SUMMARY: AddressSanitizer: 1319632 byte(s) leaked in 372 allocation(s).
make[1]: *** [Makefile:28: check] Error 1
make[1]: Leaving directory '/home/test/iniparser/test'
make: *** [Makefile:76: check] Error 2
```

**Comment by lmoellendorf** [comment]
Thank you for the report @noloader . This should be fixed on current master. See also [memcheck](https://gitlab.com/iniparser/iniparser-meta/-/jobs/6146611658).
